config:
  rcalib:
    on_hand: False
    board_frame_id: "camera/track0"
    camera_frame_id: "camera"
    flange_frame_id: "tool0_controller"
    mount_frame_id: "base"

searcher:
  streaming: true

sensors:
  streaming: true

