config:
  rcalib:
    on_hand: False
    base_frame_id: "world"
    board_frame_id: "camera/track0"
    camera_frame_id: "camera"
    flange_frame_id: "tool0_controller"

searcher:
  streaming: true

sensors:
  streaming: true

