config:
  searcher:
    solver: "feature_solver"
    solve_frame_id: "camera/capture0"
    camera_frame_id: "camera"
    base_frame_id: "base"
    master_frame_id: "camera/master0"
    capture_frame_id: "camera/capture0"
    track_frame_id: "camera/track0"
    mesh: "/cropper/mesh"
  cropper:
    base_frame_id: "base"
    capture_frame_id: ["camera","flange"]
    source_frame_id: "camera/capture"
    frame_id: "camera/capture0"
    relay: "/sensors/X1"
    ansback: "/sensors/Y1"
  rsocket:
    base_frame_id: "flange"

searcher:
  streaming: false

cropper:
  streaming: false



